apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- namespace-prod.yaml
- ../../base


labels:
- includeSelectors: true
  pairs:
    env: prod
patchesStrategicMerge:
  - wordpress-deployment-prod.yaml
