apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- namespace-dev.yaml
- ../../base


labels:
- includeSelectors: true
  pairs:
    env: dev
patchesStrategicMerge:
  - wordpress-deployment-dev.yaml
